package com.SallysBottomBarrell.service;

import java.time.LocalDate;
import java.util.List;

import javax.security.auth.login.AccountNotFoundException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.SallysBottomBarrell.entity.CreditCard;
import com.SallysBottomBarrell.entity.Products;
import com.SallysBottomBarrell.repo.CreditCardRepo;

@Service
public class CreditCardService {

	// YOU ONLY AUTOWIRE YOUR REPO OF YOUR OBJECT IN YOUR SERVIES!!!
	// NOTHING ELSE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    @Autowired
    CreditCardRepo creditCardRepo;
	
	public CreditCard save(CreditCard creditCard) {
		// Another predefined function, used to save your objects
		// Id will be autogenerated and will come back in the return after its saved

	    return creditCardRepo.save(creditCard);
	}
	
	public CreditCard update(CreditCard creditCard) throws Exception {
		// Another predefined function, used to save your objects
		// Id will be autogenerated and will come back in the return after its saved

        if(creditCard.getId() != null) {
	        return creditCardRepo.save(creditCard);
        }

        throw new Exception("Object does not exist! id not present");
	}
    
    public CreditCard findById(Integer creditCardId) throws Error {
        
    	// Find by is another predefined repo function, you can always find by the primary key
    	// when you use findById, its good practice to use the isPresent in an if check first
    	// It will tell you if a object was actually found, with true or false values, true if found, false is not
    	// It will always return an Optional Object, the creditCard will be there if found, null if not
    	// If found, give the object back with a .get() to grab it off the Optional object
    	
        if(creditCardRepo.findById(creditCardId).isPresent()) {
            return creditCardRepo.findById(creditCardId).get();
        }
        
        // if creditCard is not present, throw error so front end can handle it
        throw new Error("No creditCard id present, CreditCard not found, send an id billy, dumbass");
        
    }

	public List<CreditCard> findAll() {
		return creditCardRepo.findAll();
	}

    public void deleteById(Integer id) {
	    creditCardRepo.deleteById(id);
	}

    
    
}
